"""initial_schema

Revision ID: e15ebabb6f14
Revises: 
Create Date: 2026-04-21 20:11:49.468550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e15ebabb6f14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('white_player', sa.String(), nullable=False),
    sa.Column('black_player', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('opening_name', sa.String(), nullable=True),
    sa.Column('time_control', sa.String(), nullable=True),
    sa.Column('date_played', sa.Date(), nullable=True),
    sa.Column('pgn_content', sa.Text(), nullable=False),
    sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_analyzed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_black_player'), 'games', ['black_player'], unique=False)
    op.create_index('ix_games_black_winner', 'games', ['black_player', 'winner'], unique=False)
    op.create_index(op.f('ix_games_date_played'), 'games', ['date_played'], unique=False)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_is_analyzed'), 'games', ['is_analyzed'], unique=False)
    op.create_index(op.f('ix_games_opening_name'), 'games', ['opening_name'], unique=False)
    op.create_index(op.f('ix_games_unique_id'), 'games', ['unique_id'], unique=True)
    op.create_index(op.f('ix_games_white_player'), 'games', ['white_player'], unique=False)
    op.create_index('ix_games_white_winner', 'games', ['white_player', 'winner'], unique=False)
    op.create_index(op.f('ix_games_winner'), 'games', ['winner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_winner'), table_name='games')
    op.drop_index('ix_games_white_winner', table_name='games')
    op.drop_index(op.f('ix_games_white_player'), table_name='games')
    op.drop_index(op.f('ix_games_unique_id'), table_name='games')
    op.drop_index(op.f('ix_games_opening_name'), table_name='games')
    op.drop_index(op.f('ix_games_is_analyzed'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_date_played'), table_name='games')
    op.drop_index('ix_games_black_winner', table_name='games')
    op.drop_index(op.f('ix_games_black_player'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
